/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LibgdxTest;

import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = 800;
        config.height = 800;
        config.title = "Hello";
    }
}
